#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket..."
        /usr/bin/aesdsocket -d
        ;;
    stop)
        echo -n "Stopping aesdsocket..."
        killall /usr/bin/aesdsocket
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit $?
