#!/bin/sh
module=aesdchar
device=aesdchar
mode="664"
cd `dirname $0`
set -e
# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

if [ -e ${module}.ko ]; then
    echo "Loading local built file ${module}.ko"
    sudo insmod ./$module.ko $* || exit 1
else
    echo "Local file ${module}.ko not found, attempting to modprobe"
    sudo modprobe ${module} || exit 1
fi
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
sudo rm -f /dev/${device}
sudo mknod /dev/${device} c $major 0
sudo chgrp $group /dev/${device}
sudo chmod $mode  /dev/${device}
